[package]
name = "buckowumps"
version = "1.1.4"
edition = "2021"
authors = ["Scup st.chrysops@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = {version = "=0.4.8", features = ["audio"]}